on: [push]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0
          target: wasm32-unknown-unknown
          override: true
          components: clippy
      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: 0.9.1
          use-tool-cache: true
