on: [push]

name: build

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/toolchain@v1
        with:
          toolchain: 1.49.0
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy
