on: [push]

name: build

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
