on: [push]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: 0.9.1
          use-tool-cache: true
      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - run: npm test
      - run: npm run build
